// place files you want to import through the `$lib` alias in this folder.

import { writable } from "svelte/store";

export const theme = writable("LIGHT");
export const secondary = writable("#6c6c6c");
export const primary = writable("#fff3cf");
export const text = writable("#000000");

export const character = writable({
    character: {
        name: "",
        player: "",
        class: "",
        level: 0,
        race: "",
        alignment: "",
        deity: "",
        size: "",
        age: 0,
        gender: "",
        height: "",
        weight: "",
        eyes: "",
        hair: "",
        skin: "",
        speed: 0,
        sizeMod: 0,
    },
    stats: {
        damageReduction: 0,
        initiative: 0,
        baseAttackBonus: 0,
        spellResistance: 0,
    },
    grapple: {
        abilityModifier: "STR",
        miscellaneous: 0,
    },
    abilityModifier: {
        STR: 0,
        DEX: 0,
        CON: 0,
        INT: 0,
        WIS: 0,
        CHA: 0,
    },
    health: {
        hitPoints: 0,
        wounds: 0,
    },
    armorClass: {
        abilityModifier: "DEX",
        natural: 0,
        deflection: 0,
        miscellaneous: 0,
    },
    armor: {
        name: "",
        isEquipped: false,
        armorclassBonus: 0,
        maxDEXtoArmorclass: 0,
        penalty: 0,
        spellFailure: 0,
        speed: 0,
        weight: 0,
        specialProperties: "",
    },
    shield: {
        name: "",
        isEquipped: false,
        armorclassBonus: 0,
        weight: 0,
        penalty: 0,
        spellFailure: 0,
        specialProperties: "",
    },
    spellStats: {
        perday: {
            first: 0,
            firstBonus: 0,
            second: 0,
            secondBonus: 0,
            third: 0,
            thirdBonus: 0,
            fourth: 0,
            fourthBonus: 0,
            fifth: 0,
            fifthBonus: 0,
            sixth: 0,
            sixthBonus: 0,
            seventh: 0,
            seventhBonus: 0,
            eighth: 0,
            eighthBonus: 0,
            ninth: 0,
            ninthBonus: 0,
        },
        spellSaveDC: 0,
        abilityModifier: "WIS",
    },
    coins: {
        platinum: 0,
        gold: 0,
        silver: 0,
        copper: 0,
    },
    fortitude: {
        base: 0,
        magic: 0,
        miscellanous: 0,
        temporary: 0,
    },
    reflex: {
        base: 0,
        magic: 0,
        miscellanous: 0,
        temporary: 0,
    },
    will: {
        base: 0,
        magic: 0,
        miscellanous: 0,
        temporary: 0,
    },
    attacks: [],
    skills: [],
    inventory: [],
    languages: [],
    specialAbilities: [],
    feats: [],
    spells: [],
});